[pytest]
filterwarnings =
    ignore:GetCandlesRequest\.figi is deprecated:DeprecationWarning
    ignore:GetOrderBookRequest\.figi is deprecated:DeprecationWarning
    ignore:GetTradingStatusRequest\.figi is deprecated:DeprecationWarning
    ignore:GetLastTradesRequest\.figi is deprecated:DeprecationWarning
    ignore:PostStopOrderRequest\.figi is deprecated:DeprecationWarning
    ignore:PostOrderRequest\.figi is deprecated:DeprecationWarning
